# Site settings
title: Mülksüzleştirme Ağları
header-img: img/3.Kopru-KuzeyMarmaraOtoyolu.jpg
email: mulksuzlestirme@gmail.com
description: "Mülksüzleştirme Ağları - Türkiye'de sermaye-iktidar ilişkileri üzerine kolektif veri derleme ve haritalama"
baseurl: "/mulksuzlestirme"
url: "http://mulksuzlestirme.org"
twitter_username: mulksuzlestirme
github_username:  graphcommons
facebook_username:  graphcommons

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
